# Installation of LDOS 1.2.0
- name: Install NFS tools on all hosts
  become: true
  become_method: sudo
  gather_facts: true
  hosts: "all"
  vars:
    ansible_python_interpreter: /usr/bin/python
    
  tasks:
    # Install NFS. DFM requires an NFS mount point for .kettle with the KTR and KJB content.
    - name: Yum install nfs-utils
      raw: yum install -y nfs-utils
      when: ansible_distribution == "CentOS"
      tags: 
      - prereq

    - name: apt install nfs-common
      raw: apt install -y nfs-common
      when: ansible_distribution == "Ubuntu"
      tags: 
       - prereq

# Install LDOS 1.2.0
- name: Install LDOS over running Foundry Platform
  become: false
  gather_facts: true
  hosts: "{{ groups['installer'][0] }}"
  vars:
    logs_dir: /installers/logs
    env_properties_file: /installers/LumadaDataOpsSuite-1.2.0/installer/env.properties
    ldos_home: /installers/LumadaDataOpsSuite-1.2.0
    ldos_archive: Lumada-DataOps-Suite-1.2.0.gz
    installer_archive: Lumada-DataOps-Suite-installer-1.2.0.zip
    
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    # Checks for the logs directory
    - name: Check if 'logs' directory exists
      stat:
        path: "{{ logs_dir }}"
      register: logs
      tags: 
       - info

    - debug: 
        msg: "logs directory exists: {{ logs.stat.exists }}"
      tags: 
       - info           

    # Create a logs directory - if required
    - name: Create 'logs' Directory
      file:
       path: "{{ logs_dir }}"
       state: directory
      when: logs.stat.exists == false
      tags: 
       - info
       - install
    
    # Check for LDOS 1.2.0 directory
    - name: Check for 'LDOS 1.2.0' directory exists
      stat:
        path: "{{ ldos_home }}"
      register: ldos
      tags: 
       - info

    - debug: 
        msg: "LDOS 1.2.0 directory exists: {{ ldos.stat.exists }}"
      tags: 
       - info

    # Creates LDOS 1.2.0 install directory - if required
    - name: Create 'LDOS 1.2.0' directory
      file:
        path: "{{ ldos_home }}"
        state: directory
      when: ldos.stat.exists == false
      tags: 
       - info

    # Unarchive Lumada-DataOps_suite-1.2.0.gz
    - name: Unarchive {{ ldos_archive }}
      unarchive:
        src: "{{ ldos_home }}/{{ ldos_archive }}"
        dest: "{{ ldos_home }}"
        creates: "{{ ldos_home }}/lumada-dataops-suite"
      tags: 
       - unpack  

    # Unarchive Lumada-DataOps-Suite-Installer-1.2.0.zip
    - name: Unarchive {{ installer_archive }}
      unarchive:
        src: "{{ ldos_home }}/{{ installer_archive }}"
        dest: "{{ ldos_home }}"
      tags: 
       - unpack

    # Get Foundry secret
    - name: Get secret for solution-control-plane-sso-client
      shell: 'kubectl get secrets keycloak-client-secret-solution-control-plane-sso-client -n hitachi-solutions --template=\{\{.data.CLIENT_SECRET\}\} | base64 --decode'
      register: foundry_client_secret_obj

    - set_fact:
        foundry_client_secret={{ foundry_client_secret_obj.stdout_lines[0] }}  

    - debug:
        msg: Foundry Client Secret is {{ foundry_client_secret }}
      tags: 
       - env

    # Get the 'foundry' password 
    - name: get foundry password
      shell: "kubectl get keycloakusers -n hitachi-solutions keycloak-user -o jsonpath='{.spec.user.credentials[0].value}'"
      register: foundry_user_password_obj

    - set_fact:
        foundry_user_password={{ foundry_user_password_obj.stdout_lines[0] }}  

    - debug:
        msg: Foundry User Password is {{ foundry_user_password }}
      tags: 
       - env

    # Replace the variables in env.properties
    - name: Replace key=value pairs in env.properties file, add new values after the hostname line
      lineinfile:
        path: "{{ env_properties_file }}"
        regexp: '^[# ]*{{ item.search }}\s*=\s*'
        line: '{{ item.replace }}'
        insertafter: '^[# ]*hostname\s*=\s*'
        backup: yes
      with_items:
        - { search: 'hostname', replace: 'hostname={{ apiserver_loadbalancer_domain_name }}' }
        - { search: 'registry', replace: 'registry={{ registry_domain }}:{{ registry_port }}' }
        - { search: 'username', replace: 'username=foundry' }
        - { search: 'foundry_client_secret', replace: 'foundry_client_secret={{ foundry_client_secret }}' }
        - { search: 'password', replace: 'password={{ foundry_user_password }}' }
        - { search: 'volume_host', replace: 'volume_host={{ nfs_host }}' }
        - { search: 'volume_path', replace: 'volume_path={{ nfs_path }}' }

    # Update Hostnames in HELM charts. Hostname is defined with {{placeholder}} in Helm Charts.  
    # Careful as once defined there's no going back..!
    - name: Update LDOS Hostname
      shell: 
        chdir: "{{ ldos_home }}"
        cmd: "./installer/update-hostname.sh -c=lumada-dataops-suite/charts -h={{ apiserver_loadbalancer_domain_name }} 2>&1 | tee -a {{ logs_dir }}/update-host-name.log"
      async: 2500
      poll: 30
      register: ret
      failed_when: "ret.rc > 0 or 'no such file' in ret.stdout"
      tags: 
       - ldos

    # Upload LDOS 1.2.0 solutions to Registry.
    - name: Upload LDOS 1.2.0 Solutions to Registry
      shell: 
        chdir: "{{ ldos_home }}/lumada-dataops-suite"
        cmd: "./control-plane/bin/upload-solutions.sh -C ./charts/ -I ./images/ 2>&1 | tee -a {{ logs_dir }}/upload-ldos-solution.log"
      async: 2500
      poll: 30
      register: ret
      failed_when: "ret.rc > 0 or 'no such file' in ret.stdout"
      tags: 
       - ldos

    # Install LDOS 1.2.0
    - name: Install LDOS 1.2.0
      shell: 
        chdir: "{{ ldos_home }}/installer"
        cmd: "./install.sh 2>&1 | tee -a {{ logs_dir }}/install-ldos.log"
      async: 2500
      poll: 30
      tags: 
       - ldos

    # Check for Running and Complete Pods
    - name: Confirm Install
      shell: "kubectl get pods -n hitachi-solutions | grep -i -e '[RC][uo][nm][np][il][ne]' | wc -l"
      register: foundry_pods
      tags: 
       - ldos

    # Check for Non-Running or Failing Pods
    - name: Confirm application status (URL or pods?)
      shell: "kubectl get pods -n hitachi-solutions | grep -iv -e '[RC][uo][nm][np][il][ne]'"
      register: results
      tags: 
       - ldos

    # Output URLs
    - name: LDOS URLs
      debug:
        msg: 
        - " Installation complete.... "
        - " {{ foundry_pods.stdout }} running pods"
        - " FAILING PODS: "
        - "     {{ results.stdout }}"
        - ""
        - "URL: https://{{ apiserver_loadbalancer_domain_name }}/"
        - "     as cmoore/cmoore"
      failed_when: results.stdout is defined
      tags: 
       - ldos
      
