# Installation of NFS
- name: Configure NFS export from installer
  become: true
  become_method: sudo
  gather_facts: false
  hosts: "{{ groups['nfs_host'][0] }}" 

  any_errors_fatal: true
  tasks:
    - name: Install NFS
      shell: yum install -y nfs-utils
      tags: 
       - install

    - name: Create /etc/exports file for {{ nfs_path }}
      shell: |
        mkdir -p {{ nfs_path }};
        touch {{ nfs_path }}/kettle.properties
        echo "{{ nfs_path }} *(rw,sync,no_subtree_check,insecure)" >> /etc/exports 
      tags: 
       - install

    - name: Start nfs 
      shell: |
        systemctl enable nfs-server;
        systemctl start nfs-server;
        exportfs -a;
      tags: 
       - install

    - name: Check nfs mounts
      shell: "showmount -e {{ groups['nfs_host'][0] }}"
      register: mounts
      tags: 
       - install
   
    - name: Showmounts
      debug:
        msg: "{{ mounts.stdout }}"
      tags: 
       - install
      
- name: Configure NFS export from installer (repeat from install as doublecheck)
  become: true
  become_method: sudo
  gather_facts: false
  hosts: "{{ groups['kube-master'][0] }}"
  
  any_errors_fatal: true
  tasks:
    - name: Install NFS
      shell: yum install -y nfs-utils
      tags: 
       - install

    - name: Check nfs mounts
      shell: "showmount -e {{ groups['nfs_host'][0] }}"
      register: mounts
      tags: 
       - install
   
    - name: Showmounts
      debug:
        msg: "{{ mounts.stdout }}"
      tags:
       - install